version: "3.8"

# distribution=$(ubuntu24.04) \
#   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
#   && curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu24.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

services:

  monailabel-server:
    build: .
    image: monailabel-server:latest
    stdin_open: true # docker run -i flag
    tty: true # docker run -t flag
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monailabel
      POSTGRES_USER: monailabel
      POSTGRES_PASSWORD: monailabel

volumes:

  postgres_data: